In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [101]:
from sklearn.datasets import make_classification

In [102]:
##creating the dataset
x,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=25)

In [103]:
pd.DataFrame(x)

0         1         2         3         4         5         6  \
0    0.985257  1.779077 -0.778148 -1.761837 -1.008162 -2.010655 -1.431984   
1   -1.152754  0.714388  0.619855  1.284150  0.618555  1.766023 -0.308164   
2    0.980528 -1.557869 -0.078433 -0.587518 -0.161787 -1.121288 -2.015469   
3    0.442038 -1.256216 -0.450806 -1.624582 -1.054400 -1.531488 -1.658716   
4   -0.419483  0.922615 -0.505804 -0.721599 -0.633071 -0.254447  1.532336   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.324343  0.191915 -1.860829 -0.950069 -0.599011 -0.941147  0.425418   
996  0.891102  0.047259  0.265525 -0.997100 -0.481351 -1.368511  1.065845   
997  0.252390  1.400808  0.317126 -1.653881 -1.126279 -1.422467 -1.820884   
998 -2.703434  0.050571 -0.781440  0.215855 -0.567360  2.032118  0.949646   
999 -0.320049 -0.048126  0.836690 -0.087155 -0.148523  0.155528  0.380720   

            7         8         9  
0   -0.190388  0.677809 -1.972336  
1    0.593122  0.722257 -2.300091  
2   -1.408993 -0.040951  1.189658  
3   -0.199110  1.101990 -0.816075  
4   -2.059119 -0.444446  0.852575  
..        ...       ...       ...  
995  0.631206  0.931123 -0.284614  
996  1.152713  0.868031 -0.213476  
997 -0.222859  0.165579  0.347450  
998  1.033581 -0.372802 -1.048820  
999  0.232926 -1.056698 -0.810721  

[1000 rows x 10 columns]

In [104]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30, random_state=42)

In [105]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [106]:
logistic.fit(x_train,y_train)

LogisticRegression()

In [107]:
y_pred=logistic.predict(x_test)
print(y_pred)

[0 1 0 1 0 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 0 1 0
 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 1 1 0 1 0
 1 1 1 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1
 1 0 0 1 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 1 0 0 1 0 1
 1 1 1 1 0 1 0 1 0 1 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1
 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1
 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 0 1 1 0 1
 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 0 1 1 0 0 0
 0 0 0 0]


In [108]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [139]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.9166666666666666
[[134  19]
 [  6 141]]
              precision    recall  f1-score   support

           0       0.96      0.88      0.91       153
           1       0.88      0.96      0.92       147

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



#Hyperparameter tunning and cross validation

In [140]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,.01]
solver=['newton-cg','lbfgs' ,'liblinear' 'sag', 'saga']

In [141]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [142]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [143]:
#gridsearch cv
grid=GridSearchCV(estimator=model,param_grid=params,scoring="accuracy",cv=cv,n_jobs=-1)

In [144]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinearsag',
                                    'saga']},
             scoring='accuracy')


In [145]:
grid.fit(x_train,y_train)

C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
200 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinearsag',
                                    'saga']},
             scoring='accuracy')

In [157]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [158]:
grid.best_score_

0.9371428571428572

In [159]:
y_pred_=grid.predict(x_test)

In [160]:
score=accuracy_score(y_test,y_pred_)
print(score)
cm=confusion_matrix(y_test,y_pred_)
print(cm)
print(classification_report(y_test,y_pred_))

0.9166666666666666
[[134  19]
 [  6 141]]
              precision    recall  f1-score   support

           0       0.96      0.88      0.91       153
           1       0.88      0.96      0.92       147

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



#Randomized search CV

In [161]:
from sklearn.model_selection import RandomizedSearchCV

In [162]:
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')

In [163]:
randomcv.fit(x_train,y_train)

C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinearsag', 'saga']},
                   scoring='accuracy')

In [164]:
randomcv.best_score_

0.9314285714285713

In [165]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 10}

In [166]:
y_pred__=randomcv.predict(x_test)

In [167]:
score=accuracy_score(y_test,y_pred__)
print(score)
cm=confusion_matrix(y_test,y_pred__)
print(cm)
print(classification_report(y_test,y_pred__))

0.9166666666666666
[[136  17]
 [  8 139]]
              precision    recall  f1-score   support

           0       0.94      0.89      0.92       153
           1       0.89      0.95      0.92       147

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

